### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by mfnalex** [bloodmc/GriefDefenderAPI#10]
Hey, it seems like this plugin shows a "no permission message" when listening to PlayerInteractEvents, even when the event is cancelled by a low priority or monitor listener. Why is that, and can this be prevented?

https://www.spigotmc.org/threads/1-12-1-16-angelchest.337000/page-16#post-3880846

**Comment by bloodmc** [comment]
This was resolved in GD 2.0. Reopen a ticket if it persists.
