### ISSUE TITLE
Changing type of Visualization not working

### ISSUE THREAD

**Issue by Sir-Will** [bloodmc/GriefDefenderAPI#11]
I'm trying to change the visual to `ClaimVisualTypes.ERROR` but it ends up showing the gold block and glowstone version instead of netherrack and redstone ore.

```java
ClaimVisual visual = claim.getClaimVisual();
visual.setType(ClaimVisualTypes.ERROR);
visual.apply(player.getUniqueId(), false);
```

**Comment by bloodmc** [comment]
This was a implementation bug and was fixed in commit https://github.com/bloodmc/GriefDefender/commit/4db8346de12915ca1fa4e6c946ee77c57a41b23e
