### ISSUE TITLE
WE CUI not showing when calling ClaimVisual#apply()

### ISSUE THREAD

**Issue by Sir-Will** [bloodmc/GriefDefenderAPI#12]
The WE CUI selection is not being shown when calling `visual.apply(player.getUniqueId(), false);`
```java
ClaimVisual visual = claim.getClaimVisual();
visual.setType(ClaimVisualTypes.ERROR);
visual.apply(player.getUniqueId(), false);
```

**Comment by bloodmc** [comment]
This was a implementation bug and was fixed in commit https://github.com/bloodmc/GriefDefender/commit/4db8346de12915ca1fa4e6c946ee77c57a41b23e
