### ISSUE TITLE
Still no getFinalPermission

### ISSUE THREAD

**Issue by Sir-Will** [bloodmc/GriefDefenderAPI#13]
The API still doesn't provide a way to access `getFinalPermission` which I already reported 8 months ago: https://github.com/bloodmc/GriefDefenderAPI/issues/4

`getActiveFlagPermissionValue` doesn't provide the same result as `getFinalPermission`.

Both of the method calls below return that the player doesn't have permission in his own claim.
```java
Subject subject = GriefDefender.getCore().getSubject(player.getUniqueId().toString());
GriefDefender.getPermissionManager().getActiveFlagPermissionValue(claim, subject, Flags.BLOCK_BREAK, subject, null, new HashSet<>(), true);
claim.getActiveFlagPermissionValue(Flags.BLOCK_BREAK, GriefDefender.getCore().getUser(player.getUniqueId()), null, null, new HashSet<>(), TrustTypes.ACCESSOR, true);
```

**Comment by bloodmc** [comment]
Fixed in GD 2.0.
