### ISSUE TITLE
java.lang.NoClassDefFoundError: com/flowpowered/math/vector/Vector3i

### ISSUE THREAD

**Issue by Baktus79** [bloodmc/GriefDefenderAPI#14]
Is this no longer available for 3rd party plugins from GriefDefender? Do I have to attach this myself?

GriefDefender 2.0.0

```
Caused by: java.lang.NoClassDefFoundError: com/flowpowered/math/vector/Vector3i
	at no.vestlandetmc.BanFromClaim.commands.griefdefender.BfcCommandGD.onCommand(BfcCommandGD.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-132]
	... 21 more
```

**Comment by bloodmc** [comment]
As GD is loaded within a jar at runtime, all API dependencies that other plugins might use had to be relocated. 

All plugins have to do is relocate to match what GD has

Use GDHooks as a primary model

See https://github.com/bloodmc/GDHooks/blob/master/bukkit/build.gradle#L148-L174

**Comment by bloodmc** [comment]
I'll keep this open if you have any further problems.

**Comment by Baktus79** [comment]
This is great, and the relocation will resolve a few other issues I have regarding conflicts with other plugins.
Thanks for your help!
