### ISSUE TITLE
Publish API to the central repository

### ISSUE THREAD

**Issue by josephjthomas** [bloodmc/GriefDefenderAPI#15]
Do you think you can publish the API to the central maven repository? Jitpack has lots of outages and is by far not as reliable as the the central repository (https://repo.maven.apache.org/). I encountered several outages over the past months so I couldn't compile my projects.
I hope this is something you would consider.

The Sonatype team have heavily reworked their standards and requirements. They allow hosting of almost any open source software nowadays, whether it's an API, a library or a dependency for something else.

Thanks for considering it.

**Comment by bloodmc** [comment]
I agree that Jitpack is very unreliable. However, I do have API available on maven repo here https://repo.glaremasters.me/repository/bloodshot

For more info, see https://github.com/bloodmc/GriefDefender/wiki/API

Let me know if this works for you.

**Comment by josephjthomas** [comment]
That looks like it works, but I'm afraid of future changes. I prefer the central repository, because it's been proven to be _the_ repository to go to nowadays, according to its stats. I have had some bad experience with past repositories, because they just vanished over night, the owner went MIA or just stopped caring about it (not calling out names here).

**Comment by bloodmc** [comment]
Glare runs this repository and I communicate with him closely. If he were to close the repo, he would let me know beforehand. It has been up since GD was first released for Bukkit with minimal downtime.

**Comment by NotMyFault** [comment]
+1 from me

I'm working with the GD API as well and had to strip certain dependencies on an regular base, because JitPack deployed none or false artifacts. Definitely not the way to go when you're working with several people on projects, rely on GitHub actions for deployment etc etc.

But good to see I can remove JitPack at least for this dependency, thanks for your work :)

**Comment by bloodmc** [comment]
DEV branch has been updated with relocation changes. You will no longer be required to relocate to use GD's API as the relocated dependencies will now be provided with the jar. I'll close this ticket once GD 2.1.0 is released. Let me know if you run into any more issues.

**Comment by bloodmc** [comment]
Fixed in 2.1.0-SNAPSHOT

**Comment by bloodmc** [comment]
Woops, I see the original issue was to put API on central maven. I'll keep this open until I can work that out. For now, the workaround is to use glare's maven repo above.

**Comment by bloodmc** [comment]
GriefDefenderAPI is now available on sonatype OSSRH for -SNAPSHOT releases.

https://s01.oss.sonatype.org/#nexus-search;quick~com.griefdefender
