### ISSUE TITLE
Distribution via Maven Repository

### ISSUE THREAD

**Issue by AuroraLS3** [bloodmc/GriefDefenderAPI#2]
Hello.

I was wondering if it would be possible to distribute the API artifact on a public maven repository.

[Bintray](https://bintray.com/) or [JitPack](https://jitpack.io/) offer free maven repository hosting for open source projects

**Comment by bloodmc** [comment]
The API is already available on `repo.glaremasters.me` maven repository. Also, nothing stops you from using jitpack in your gradle build setup.
