### ISSUE TITLE
Method must have an Event as its first parameter

### ISSUE THREAD

**Issue by Sir-Will** [bloodmc/GriefDefenderAPI#3]
hey,

I'm unable to use the events as I'm getting the error that the GD events are not a instance of the Sponge events.

Am I supposed to a different Listener then `org.spongepowered.api.event.Listener` ?

**Comment by bloodmc** [comment]
GriefDefender's API is cross-platform and does not use Sponge's API.  It uses Kyori's Event library. See https://github.com/bloodmc/ClaimTweaks for an example on how to migrate to new event API.

**Comment by Sir-Will** [comment]
Ah, thanks.

Is there a better way to get the player from the `CreateClaimEvent`, other than getting it from the claim?

```java
final Player player = Sponge.getServer().getPlayer(event.getClaim().getOwnerUniqueId()).orElse(null);
```
