### ISSUE TITLE
ClaimVisual and getFinalPermission missing

### ISSUE THREAD

**Issue by Sir-Will** [bloodmc/GriefDefenderAPI#4]
I'm missing API access to the claim visualization. With GriefPrevention I imported the complete project and used the code below to create a own visualization.
```java
Optional<PlayerData> playerData = getGriefPrevention().getGlobalPlayerData(player.getUniqueId());
if (playerData.isPresent()) {
    Visualization visualization = new Visualization((GPClaim) claim, VisualizationType.ERROR);
    visualization.createClaimBlockVisuals(player.getLocation().getBlockY(), player.getLocation(), (GPPlayerData) playerData.get());
    visualization.apply(player, false);
}
```
---
The API doesn't seem to provide the `getFinalPermission()` method. In GriefPrevention there was this method below to check if a player can break blocks in a claim. Is there a existing replacement for this?
```java
GPPermissionHandler.getClaimPermission(null, null, (GPClaim) claim, GPPermissions.BLOCK_BREAK, null, null, player, TrustType.ACCESSOR, true);
```

**Comment by bloodmc** [comment]
Claim visualizations were never part of the API but I plan on adding it soon.

As for `getFinalPermission` , use `getActiveFlagPermission` in PermissionManager.

**Comment by Sir-Will** [comment]
I assume you meant `getActiveFlagPermissionValue` like
````java
claim.getActiveFlagPermissionValue(Flags.BLOCK_BREAK, GriefDefender.getCore().getUser(player.getUniqueId()), null, null, new HashSet<>(), TrustTypes.ACCESSOR, true)
````

**Comment by Sir-Will** [comment]
@bloodmc this doesn't seem to be working for me. It returns false for the own claim.
